### ISSUE TITLE
When writing your code.

### ISSUE THREAD

**Issue by farishkash** [coffeeNcake/jammming#1]
https://github.com/coffeeNcake/jammming/blob/master/src/components/searchbar/SearchBar.js#L7
Avoid one line statements like this for objects

`this.state = {term: ''};`

This is cleaner and emphasizes the idea that you can expand your state. 

```
this.state = {
      term: ''
    };
```

**Comment by coffeeNcake** [comment]
Noted - thank you for the feedback!
