### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [coffeeNcake/jammming#2]
Overall great job.

I noticed you started to do the feature requests but this didn't come to me as a feature request review just Jamming.

Ironically Elise and I went over this project a few days ago because there was some issues I was helping her with and it looks like it we were successful.

My only concern is this section of code in your app.js

savePlaylist() {
    let trackURIs = this.state.playlistTracks.map(track => track.uri);
    Spotify.savePlaylist(this.state.playlistName, trackURIs).then(() => {
      this.setState({
        playlistName: 'New Playlist',
        //playlistTracks: [],
        searchResults: []
      });
    });
  }

Is it your intention to wipe out the searchResults when you save a playlist?  Thinking more from a UX point of view, do you feel this is a good way to go about this?

If this is for the feature request, I didn't see that as being request.  I am usually always on advisor chat on the weekend days, feel free to reach out to me then if you want to discuss this further.

Once again great job and something for you to think about as you will start venturing into making your own react apps.

**Comment by coffeeNcake** [comment]
Thank you for your feedback Farish.

The searchResults were cleared as per Step 95 in the instructions.  I also left a note in the "Notes for Reviewer" section in the Readme file.

![image](https://user-images.githubusercontent.com/27825788/31616885-f037bbc0-b25b-11e7-80f7-03c39917d6db.png)

From a UX point of view, in my opinion, I would have left the searchResults and the playlistTracks alone. I
contemplated leaving them but decided the requirements took precedence and cleared the values.  Perhaps, this is something that may be changed for the next class, if the UX doesn't make sense.
